#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Drop.Droid.Resource", IsApplication=true)]

namespace Drop.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Drop.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Drop.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Drop.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Drop.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Drop.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Drop.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Drop.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Drop.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Drop.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Drop.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Drop.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Drop.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Drop.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Drop.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Drop.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Drop.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Drop.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Drop.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Drop.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Drop.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Drop.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Drop.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Drop.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Drop.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Drop.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Drop.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int back = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fromLeft = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fromRight = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int toLeft = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int toRight = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_top = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_blue1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_blue2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_bottom_orange = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_colleps = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_date = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_drop_detail = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_home_btn = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_home_btn_content = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_orange = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg_pw = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bg_textfield = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bg_tool_button = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_back = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_drop_item = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_drop_nearby = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_right = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_errorstatus = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_successstatus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_audio = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon_check = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon_colleps = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon_drop1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon_drop10 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int icon_drop11 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon_drop12 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int icon_drop13 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon_drop2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int icon_drop3 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int icon_drop4 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int icon_drop5 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int icon_drop6 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int icon_drop7 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int icon_drop8 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon_drop9 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon_drop_setting = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon_expend = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_favorite = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_image_sel = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_image_unsel = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_link = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_link_sel = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_link_unsel = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon_location = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int icon_lock = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon_minus = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icon_plus = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int icon_share_fb = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int icon_share_ins = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int icon_share_mail = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int icon_share_tw = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int icon_smile = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int icon_text_sel = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int icon_text_unsel = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int icon_uncheck = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int icon_video = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int icon_video_sel = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int icon_video_unsel = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int item_CheckBox = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int item_colleps = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int roundedbg = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int roundedbgdark = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Splash = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int ActionBack = 2131165186;
			
			// aapt resource value: 0x7f070039
			public const int ActionCollpseExpire = 2131165241;
			
			// aapt resource value: 0x7f070021
			public const int ActionCollpseIcon = 2131165217;
			
			// aapt resource value: 0x7f07002a
			public const int ActionCollpseLocation = 2131165226;
			
			// aapt resource value: 0x7f070016
			public const int ActionCollpseName = 2131165206;
			
			// aapt resource value: 0x7f070035
			public const int ActionCollpsePassword = 2131165237;
			
			// aapt resource value: 0x7f070030
			public const int ActionCollpsePermission = 2131165232;
			
			// aapt resource value: 0x7f07003c
			public const int ActionCollpseShare = 2131165244;
			
			// aapt resource value: 0x7f07002c
			public const int ActionCurrentLocation = 2131165228;
			
			// aapt resource value: 0x7f07002f
			public const int ActionCustomLocation = 2131165231;
			
			// aapt resource value: 0x7f070023
			public const int ActionDefaultIcon1 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int ActionDefaultIcon2 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int ActionDefaultIcon3 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int ActionDefaultIcon4 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int ActionDefaultIcon5 = 2131165223;
			
			// aapt resource value: 0x7f070045
			public const int ActionDropItem = 2131165253;
			
			// aapt resource value: 0x7f070055
			public const int ActionDropNearby = 2131165269;
			
			// aapt resource value: 0x7f07005a
			public const int ActionDropSetting = 2131165274;
			
			// aapt resource value: 0x7f070032
			public const int ActionEveryone = 2131165234;
			
			// aapt resource value: 0x7f070015
			public const int ActionGotoLink = 2131165205;
			
			// aapt resource value: 0x7f07005c
			public const int ActionHome = 2131165276;
			
			// aapt resource value: 0x7f07001e
			public const int ActionItem = 2131165214;
			
			// aapt resource value: 0x7f070063
			public const int ActionLoginAnonymously = 2131165283;
			
			// aapt resource value: 0x7f07000d
			public const int ActionLoginUsingFacebook = 2131165197;
			
			// aapt resource value: 0x7f070033
			public const int ActionOnlyMe = 2131165235;
			
			// aapt resource value: 0x7f070037
			public const int ActionPassword = 2131165239;
			
			// aapt resource value: 0x7f070014
			public const int ActionPlayVideo = 2131165204;
			
			// aapt resource value: 0x7f070034
			public const int ActionSpecificUser = 2131165236;
			
			// aapt resource value: 0x7f070064
			public const int Video = 2131165284;
			
			// aapt resource value: 0x7f070051
			public const int aniBgView = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int aniContentView = 2131165266;
			
			// aapt resource value: 0x7f07001b
			public const int btnDropImageSymbol = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int btnDropLinkSymbol = 2131165213;
			
			// aapt resource value: 0x7f07001a
			public const int btnDropTextSymbol = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int btnDropVideoSymbol = 2131165212;
			
			// aapt resource value: 0x7f07000f
			public const int checkBox1 = 2131165199;
			
			// aapt resource value: 0x7f07004e
			public const int iconMyLocation = 2131165262;
			
			// aapt resource value: 0x7f070062
			public const int imageView1 = 2131165282;
			
			// aapt resource value: 0x7f070040
			public const int imageView10 = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int imageView11 = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int imageView12 = 2131165252;
			
			// aapt resource value: 0x7f070053
			public const int imageView3 = 2131165267;
			
			// aapt resource value: 0x7f070056
			public const int imageView4 = 2131165270;
			
			// aapt resource value: 0x7f07005b
			public const int imageView5 = 2131165275;
			
			// aapt resource value: 0x7f070029
			public const int imageView8 = 2131165225;
			
			// aapt resource value: 0x7f07003e
			public const int imageView9 = 2131165246;
			
			// aapt resource value: 0x7f070048
			public const int imeisearch = 2131165256;
			
			// aapt resource value: 0x7f070028
			public const int imgDropIcon = 2131165224;
			
			// aapt resource value: 0x7f070007
			public const int imgImage = 2131165191;
			
			// aapt resource value: 0x7f07002d
			public const int lblLocationLat = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int lblLocationLog = 2131165230;
			
			// aapt resource value: 0x7f070009
			public const int lblName = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int lblText = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout10 = 2131165201;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout11 = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout12 = 2131165192;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout13 = 2131165202;
			
			// aapt resource value: 0x7f07003f
			public const int linearLayout14 = 2131165247;
			
			// aapt resource value: 0x7f070041
			public const int linearLayout15 = 2131165249;
			
			// aapt resource value: 0x7f070043
			public const int linearLayout16 = 2131165251;
			
			// aapt resource value: 0x7f070054
			public const int linearLayout17 = 2131165268;
			
			// aapt resource value: 0x7f070057
			public const int linearLayout19 = 2131165271;
			
			// aapt resource value: 0x7f070050
			public const int linearLayout2 = 2131165264;
			
			// aapt resource value: 0x7f070058
			public const int linearLayout20 = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int linearLayout21 = 2131165273;
			
			// aapt resource value: 0x7f07004c
			public const int linearLayout22 = 2131165260;
			
			// aapt resource value: 0x7f07004f
			public const int linearLayout23 = 2131165263;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout3 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout4 = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout5 = 2131165195;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout6 = 2131165215;
			
			// aapt resource value: 0x7f07005d
			public const int linearLayout7 = 2131165277;
			
			// aapt resource value: 0x7f070046
			public const int linearLayout8 = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int linearLayout9 = 2131165255;
			
			// aapt resource value: 0x7f070060
			public const int loadingImage = 2131165280;
			
			// aapt resource value: 0x7f07005e
			public const int loadingProgressBar = 2131165278;
			
			// aapt resource value: 0x7f070061
			public const int loadingProgressWheel = 2131165281;
			
			// aapt resource value: 0x7f07004b
			public const int map = 2131165259;
			
			// aapt resource value: 0x7f07004a
			public const int map_place_box = 2131165258;
			
			// aapt resource value: 0x7f070001
			public const int relativeLayout1 = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int relativeLayout2 = 2131165196;
			
			// aapt resource value: 0x7f07004d
			public const int relativeLayout3 = 2131165261;
			
			// aapt resource value: 0x7f070005
			public const int scrollView1 = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int textView1 = 2131165187;
			
			// aapt resource value: 0x7f070020
			public const int textView2 = 2131165216;
			
			// aapt resource value: 0x7f070019
			public const int textView4 = 2131165209;
			
			// aapt resource value: 0x7f07003b
			public const int textView5 = 2131165243;
			
			// aapt resource value: 0x7f070013
			public const int textView7 = 2131165203;
			
			// aapt resource value: 0x7f07005f
			public const int textViewStatus = 2131165279;
			
			// aapt resource value: 0x7f070017
			public const int txtDescription = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int txtName = 2131165198;
			
			// aapt resource value: 0x7f070038
			public const int txtPassword = 2131165240;
			
			// aapt resource value: 0x7f070049
			public const int txtSearchLocation = 2131165257;
			
			// aapt resource value: 0x7f070065
			public const int videoView = 2131165285;
			
			// aapt resource value: 0x7f07003a
			public const int viewExpiry = 2131165242;
			
			// aapt resource value: 0x7f070022
			public const int viewICON = 2131165218;
			
			// aapt resource value: 0x7f07002b
			public const int viewLocation = 2131165227;
			
			// aapt resource value: 0x7f070010
			public const int viewName = 2131165200;
			
			// aapt resource value: 0x7f070036
			public const int viewPassword = 2131165238;
			
			// aapt resource value: 0x7f070031
			public const int viewPermission = 2131165233;
			
			// aapt resource value: 0x7f07003d
			public const int viewShare = 2131165245;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DropDetailLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DropItemActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DropLocationLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loading = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loadingimage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loadingprogress = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LoginActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NearbyLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PlayVideoLayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int app_id = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
